### ISSUE TITLE
add the htag's todomvc ?

### ISSUE THREAD

**Issue by manatlan** [metaperl/pure-python-web-development#2]
Hi @metaperl ...

Just found the page https://metaperl.github.io/pure-python-web-development/todomvc.html 

And i've made a "TODOMVC" with **htag** ;-)
Here it is : https://github.com/manatlan/htag/blob/main/examples/todomvc.py

this "todomvc" is integrated in my pyscript/html demo's page
https://raw.githack.com/manatlan/htag/main/examples/pyscript_demo.html?115-todomvc.py
(so it will be possible to edit/test/run (like repl, but on client side, with pyscript tech ! no python required!))

if you have no time, i could submit a PR, sure!

---------------------
to inform you about recent htag's developments.
- will release a "1.0.0" soon
- I've just created another "htag runner" (outside of the main htag module) named [htagweb](https://github.com/manatlan/htagweb), which is available as another lib on pypi, which provide a more robust "http server" for hosting "htag app" over the web (with sessions, real process management, multiple gunicorn workers, etc ...). On which, it's easy to manage an oauth2 flow (with authlib), I will provide an example soon. It was not the main goal of htag at start, but now, it's a reality : htag's apps can be served, in a decent way on the web ... see https://www.mlan.fr (which is my main dev/server for "htag on the web").

best regards

**Comment by metaperl** [comment]
Hi, each time I hear an update on a pure python web framework library, I move it to the top of the list of libraries for that class. As a result [I have just moved Htag to the top of Class B](https://github.com/metaperl/pure-python-web-development/commit/44482c197f73b943b321ff8602dbb504a1b8392b). 

Please make sure to update your fork of the repo before submitting the PR. And yes, I do welcome it.
