### ISSUE TITLE
New Framework Recommended: FastUI

### ISSUE THREAD

**Issue by hasansezertasan** [metaperl/pure-python-web-development#6]
Great project 🚀🚀🚀, it helped me discover a lot.

I believe, this project should also mention FastUI

**Comment by metaperl** [comment]
Thanks for mentioning this framework. I'm glad you are benefitting from the survey. I looked over FastUI... I had not heard of it before... I suppose it would go in Class B at the moment? It definitely has some promise for Class A for the future.

What do you think?

**Comment by hasansezertasan** [comment]
> Thanks for mentioning this framework. I'm glad you are benefitting from the survey.

You're welcome 😇 

> I looked over FastUI... I had not heard of it before... I suppose it would go in Class B at the moment? It definitely has some promise for Class A for the future.

I agree with you.

**Comment by hasansezertasan** [comment]
Hey @metaperl, I also recommend you to check [liveviews/liveviews: Phoenix LiveView workalikes for different languages and frameworks](https://github.com/liveviews/liveviews?tab=readme-ov-file#python) repo, there are quite interesting packages and I believe some of them may fit the scope of this survey.

**Comment by hasansezertasan** [comment]
Hey @metaperl, how is it going on?

Today I discovered a new technology called [flect](https://github.com/Chaoyingz/flect). It's quite similar to FastUI, I think you should also include this package in the survey.

**Comment by metaperl** [comment]
Yes, I'm struggling to keep up with all the new frameworks. And the Class A, B, C thing maybe is not the best way to stratify them?

**Comment by metaperl** [comment]
Hi, I've acknowledged you in the end notes and added Liveviews - https://github.com/metaperl/pure-python-web-development/commit/efc73a30ceebfc2380cf9957839f410541d81fb5#diff-33dc5ffcfd3a55a2778b14da19b4711509c04a5b5223cdccaaef74c0511eb1e8

still figuring out how to add flect and FastUI...

**Comment by metaperl** [comment]
> Hey @metaperl, I also recommend you to check [liveviews/liveviews: Phoenix LiveView workalikes for different languages and frameworks](https://github.com/liveviews/liveviews?tab=readme-ov-file#python) repo, there are quite interesting packages and I believe some of them may fit the scope of this survey.

Hypergen for Django in that same list of resources is even more impressive than Django LiveViews in terms of being production ready IMHO.

**Comment by metaperl** [comment]
> > Thanks for mentioning this framework. I'm glad you are benefitting from the survey.
> 
> You're welcome 😇
> 
> > I looked over FastUI... I had not heard of it before... I suppose it would go in Class B at the moment? It definitely has some promise for Class A for the future.
> 
> I agree with you.

I added FastUI to class C. It is very immature at the moment.

**Comment by metaperl** [comment]
> Hey @metaperl, how is it going on?
> 
> Today I discovered a new technology called [flect](https://github.com/Chaoyingz/flect). It's quite similar to FastUI, I think you should also include this package in the survey.

Added to Class C.

**Comment by hasansezertasan** [comment]
> Yes, I'm struggling to keep up with all the new frameworks. And the Class A, B, C thing maybe is not the best way to stratify them?

😆, yep there are too many and the amount of new frameworks is increasing. I think Class A/B/C stratification sounds good enough at the moment but maybe including a small comparison table like https://github.com/jowilf/starlette-admin/discussions/333#discussion-5746893 could be quite helpful. Like, which frameworks use which technologies to communicate with the backend, or do those frameworks have anything to do with the backend (FastUI doesn't do anything with the backend, it's backend/framework agnostic).


> Hi, I've acknowledged you in the end notes and added Liveviews - [efc73a3#diff-33dc5ffcfd3a55a2778b14da19b4711509c04a5b5223cdccaaef74c0511eb1e8](https://github.com/metaperl/pure-python-web-development/commit/efc73a30ceebfc2380cf9957839f410541d81fb5#diff-33dc5ffcfd3a55a2778b14da19b4711509c04a5b5223cdccaaef74c0511eb1e8)

Thank you for mentioning me on the survey 😍.

> Hypergen for Django in that same list of resources is even more impressive than Django LiveViews in terms of being production ready IMHO.

I totally agree. There are great projects to build applications with. I haven't got much experience with Django but I totally want to use/learn (whatever you say) it one day.

> I added FastUI to class C. It is very immature at the moment.

Good fit.

> Added to Class C.

Fantastic!

Closing the issue, since it's done! Thank you for your interest and great work 🚀.
