### ISSUE TITLE
New Framework Recommended: Ludic

### ISSUE THREAD

**Issue by hasansezertasan** [metaperl/pure-python-web-development#7]
There is an HTMX hype going on and there are new packages produced to use with. One of them is [Ludic](https://github.com/paveldedik/ludic).

It's a quite new package (less than 10 days old). It proposes an unusual syntax for building HTML using Python, so I do recommend checking it out.

**Comment by hasansezertasan** [comment]
Another great-looking project: [hyperdiv/hyperdiv: Build reactive web UIs in Python](https://github.com/hyperdiv/hyperdiv)

**Comment by hasansezertasan** [comment]
Check out these other projects:

- [scriptiot/evue: Evue is a high-performance gui framework base an html/css which can run on windows/linux/macos/web/ios/andriod/rtos! Write once, run everywhere! .](https://github.com/scriptiot/evue)
- [Zomatree/Kine: React like agnostic GUI framework for Python](https://github.com/Zomatree/Kine)

**Comment by metaperl** [comment]
> There is an HTMX hype going on and there are new packages produced to use with. One of them is [Ludic](https://github.com/paveldedik/ludic).
> 
> It's a quite new package (less than 10 days old). It proposes an unusual syntax for building HTML using Python, so I do recommend checking it out.

I saw Ludic when it was announced on reddit. I would be surprised if anything significant is ever developed in it. The developer of HTMX had concerns that Ludic was using f-strings to do templating.

I am overburdened with keeping t his guide up to date. So I only add things for projects that look promising.

**Comment by metaperl** [comment]
> Check out these other projects:
> 
> * [scriptiot/evue: Evue is a high-performance gui framework base an html/css which can run on windows/linux/macos/web/ios/andriod/rtos! Write once, run everywhere! .](https://github.com/scriptiot/evue)
> * [Zomatree/Kine: React like agnostic GUI framework for Python](https://github.com/Zomatree/Kine)

you might want to put them in a separate ticket. But evue has not been updated for over 1 year and has 3 open issues and unmerged PRs. (my way of getting out of adding it).

kine looks a little more promising, having received an update 6 months ago.

**Comment by hasansezertasan** [comment]
> I saw Ludic when it was announced on reddit. I would be surprised if anything significant is ever developed in it. The developer of HTMX had concerns that Ludic was using f-strings to do templating.

Well, I didn't know about f-string stuff...

Is this the thread you were talking about? [Introducing Ludic: web development with HTMX, async, components, templating with f-strings : r/Python](https://www.reddit.com/r/Python/comments/1b9qbjt//)

> I am overburdened with keeping t his guide up to date. So I only add things for projects that look promising.

I see, I believe it's promising but it has less activity due to it's stargazer count.

**Comment by hasansezertasan** [comment]
> you might want to put them in a separate ticket. But evue has not been updated for over 1 year and has 3 open issues and unmerged PRs. (my way of getting out of adding it).

I'll do it when I get a chance 😆.

> kine looks a little more promising, having received an update 6 months ago.

Alright then.

**Comment by metaperl** [comment]
Ludic has been added here - https://www.reddit.com/r/purepythonwebdev

**Comment by metaperl** [comment]
> Check out these other projects:
> 
> * [scriptiot/evue: Evue is a high-performance gui framework base an html/css which can run on windows/linux/macos/web/ios/andriod/rtos! Write once, run everywhere! .](https://github.com/scriptiot/evue)
> * [Zomatree/Kine: React like agnostic GUI framework for Python](https://github.com/Zomatree/Kine)

both have been added - https://www.reddit.com/r/PurePythonWebDev/

**Comment by metaperl** [comment]
Kine, Evue and Ludic have been added - https://github.com/metaperl/pure-python-web-development/discussions/categories/specific-framework-discussion
