### ISSUE TITLE
Rio

### ISSUE THREAD

**Issue by Pablo2m** [metaperl/pure-python-web-development#9]
This framework seems promising, I'm still testing it https://rio.dev/

**Comment by metaperl** [comment]
Yes, it does look impressive. I dont have time to maintain this guide. There really needs to be a different way to present all these frameworks. I added Rio to a subreddit for Pure Python frameworks - https://www.reddit.com/r/PurePythonWebDev/

I am upset that a post cannot have multiple flairs. But I guess I have to deal with it.

I just dont have time to edit a guide that doesnt seem to be what people use to choose a framework.

**Comment by metaperl** [comment]
I've decided to create discussion threads for each framework: the more posts to the thread, the more active the framework. This way, dead frameworks will automatically sort themselves to the bottom. Here is the Rio thread - https://github.com/metaperl/pure-python-web-development/discussions
